CREATE TABLE DOLLS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	HEIGHT VARCHAR(100),
    NAME VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE FLOAT
);

CREATE TABLE TAGS (
	DOLL_ID INT,
    TAGNAME VARCHAR(100)
)

